name: Docs CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch and only for the docs folder
  push:
    branches: [ "main" ]
    paths:
      - docs/**
  pull_request:
    branches: [ "main" ]
    paths:
      - docs/**
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# grab commit message
env:
  commitMsg: ${{ github.event.head_commit.message }}

# Copy the contents to the ris-DevOps-DocsPortal repo ready for publishing to code site.
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Push docs folder
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'docs/'
        destination_repo: 'risualDevOps/ris-DevOps-DocsPortal'
        destination_folder: 'portal/content/DemoSite/'
        user_email: ${{ secrets.USER_EMAIL }}
        user_name: ${{ secrets.USER_NAME }}
        commit_message: echo "[DemoSite] Update Documentation for Site. Commit Message - $commitMsg"
        git_server: 'github.com'
