name: Docs CI

# Controls when the workflow will run
on:
  # Triggers the workflow pull request merge events but only for the "main" branch and only for the docs folder
  pull_request:
    types:
      - closed
    branches: [ "main" ]
    paths:
      - docs/**
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Copy the contents to the ris-DevOps-DocsPortal repo ready for publishing to code site.
jobs:
  copy-file:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Push docs folder
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'docs/'
        destination_repo: 'risualDevOps/ris-DevOps-DocsPortal'
        destination_folder: 'portal/content/DemoSite/'
        user_email: ${{ secrets.USER_EMAIL }}
        user_name: ${{ secrets.USER_NAME }}
        commit_message: ${{format('[DemoSite Docs] Commit - {0}', github.event.head_commit.message )}}
        git_server: 'github.com'
