name: Docs CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch and only for the docs folder
  push:
    branches: [ "main" ]
    paths:
      - docs/**
  pull_request:
    branches: [ "main" ]
    paths:
      - docs/**
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Copy the contents to the ris-DevOps-DocsPortal repo ready for publishing to code site.
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Push docs folder
      uses: datalbry/copy_folder_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'docs'
        destination_repo: 'risualDevOps/ris-DevOps-DocsPortal'
        destination_folder: 'portal/content/docs/DemoSiteDocumentation'
        user_email: 'hello@joetomkinson.dev'
        user_name: 'JoeTomkinson'
        commit_msg: '[DemoSite] Update Documentation for Site.'
        git_server: 'github.com'
