name: Docs CI

# Controls when the workflow will run
on:
  # Triggers the workflow pull request merge events but only for the "main" branch and only for the docs folder
  pull_request:
    types:
      - closed
    branches: [ "main" ]
    paths:
      - docs/**
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Copy the contents to the ris-DevOps-DocsPortal repo ready for publishing to code site.
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create pull request
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'docs/**'
        destination_repo: 'risualDevOps/ris-DevOps-DocsPortal'
        destination_folder: 'portal/content'
        destination_base_branch: 'main'
        destination_head_branch: ${{ format('docs-update - {0}{1}', github.run_id, github.run_attempt) }}
        user_email:  ${{ secrets.USER_EMAIL }}
        user_name:  ${{ secrets.USER_NAME }}
